project:
  type: website
  output-dir: docs

website:
  title: "Club~Del~Código"
  navbar:
    right:
      - about.qmd
      - contacto.qmd
      - recursos.qmd
      - text: "Reuniones"
        menu: 
          - reunion1.qmd
          - reunion2.qmd
          - reunion3.qmd
          - reunion4.qmd
          - reunion5.qmd
      - galeria.qmd
      - icon: github
        href: https://github.com/toninif/clubdelcodigo/blob/main/README.md
format:
  html:
    theme: 
      light: minty
      dark: vapor
    css: styles.css
    toc: true
    from: markdown+emoji
    code-fold: show
    code-summary: "Ver/Ocultar código"
    code-tools: true
    code-block-border-left: true
    code-line-numbers: true
    code-link: true

editor: visual

