project:
  type: website
  output-dir: docs

website:
  title: "Club~Del~CÃ³digo"
  navbar:
    right:
      - about.qmd
      - recursos.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: 
      light: minty
      dark: vapor
    css: styles.css

editor: visual

