project:
  type: website
  output-dir: docs

website:
  title: "Club~Del~CÃ³digo"
  navbar:
    right:
      - about.qmd
      - recursos.qmd
      - text: "Reuniones"
        menu: 
          - reunion1.qmd
          - reunion2.qmd
          - reunion3.qmd
          - reunion4.qmd
          - reunion5.qmd
      - icon: github
        href: https://github.com/toninif/clubdelcodigo/blob/main/README.md
format:
  html:
    theme: 
      light: minty
      dark: vapor
    css: styles.css
    toc: true
    from: markdown+emoji

editor: visual

